/**
 * mockStudents.js
 * Mock data for LPU (Lovely Professional University) students.
 * Registration numbers follow LPU format: 12XXXXXXX
 * Hostel blocks follow LPU campus numbering (Boys: 32,34,36,38 | Girls: 33,35,37,39)
 */

export const mockStudents = [
  {
    id: 1,
    name: "Aarav Sharma",
    regNo: "12312501",
    email: "aarav.sharma@lpu.in",
    program: "B.Tech (CSE)",
    school: "School of Computer Science & Engineering",
    year: 3,
    gender: "Male",
    roomPreference: "Double",
    hostelBlock: "32",
    roomNo: "32-204",
    interests: ["Coding", "Gaming", "Music"],
    sleepSchedule: "Night Owl",
    cleanliness: "Very Neat",
    studyHabits: "Quiet Study",
    cgpa: 8.9,
    hometown: "Delhi",
    matchScore: 94,
    avatar: "AS",
    avatarColor: "bg-indigo-500",
    allocationStatus: "Allocated",
    matchStatus: "Matched",
  },
  {
    id: 2,
    name: "Priya Patel",
    regNo: "12312748",
    email: "priya.patel@lpu.in",
    program: "B.Tech (ECE)",
    school: "School of Electronics & Electrical Engineering",
    year: 3,
    gender: "Female",
    roomPreference: "Single",
    hostelBlock: "33",
    roomNo: "33-112",
    interests: ["Reading", "Yoga", "Sketching"],
    sleepSchedule: "Early Bird",
    cleanliness: "Neat",
    studyHabits: "Group Study",
    cgpa: 9.2,
    hometown: "Ahmedabad",
    matchScore: 88,
    avatar: "PP",
    avatarColor: "bg-pink-500",
    allocationStatus: "Allocated",
    matchStatus: "Looking",
  },
  {
    id: 3,
    name: "Rohan Mehta",
    regNo: "12313302",
    email: "rohan.mehta@lpu.in",
    program: "B.Tech (ME)",
    school: "School of Mechanical Engineering",
    year: 2,
    gender: "Male",
    roomPreference: "Double",
    hostelBlock: "34",
    roomNo: "34-310",
    interests: ["Football", "Chess", "Cooking"],
    sleepSchedule: "Night Owl",
    cleanliness: "Moderate",
    studyHabits: "Solo Study",
    cgpa: 7.8,
    hometown: "Mumbai",
    matchScore: 76,
    avatar: "RM",
    avatarColor: "bg-emerald-500",
    allocationStatus: "Allocated",
    matchStatus: "Matched",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    regNo: "12312890",
    email: "sneha.reddy@lpu.in",
    program: "B.Tech (CE)",
    school: "School of Civil Engineering",
    year: 3,
    gender: "Female",
    roomPreference: "Double",
    hostelBlock: "35",
    roomNo: "35-205",
    interests: ["Dance", "Cooking", "Photography"],
    sleepSchedule: "Early Bird",
    cleanliness: "Very Neat",
    studyHabits: "Group Study",
    cgpa: 8.4,
    hometown: "Hyderabad",
    matchScore: 91,
    avatar: "SR",
    avatarColor: "bg-orange-500",
    allocationStatus: "Allocated",
    matchStatus: "Looking",
  },
  {
    id: 5,
    name: "Karan Singh",
    regNo: "12311045",
    email: "karan.singh@lpu.in",
    program: "B.Tech (CSE-AI)",
    school: "School of Computer Science & Engineering",
    year: 4,
    gender: "Male",
    roomPreference: "Single",
    hostelBlock: "36",
    roomNo: "36-108",
    interests: ["Cycling", "Competitive Programming", "Movies"],
    sleepSchedule: "Night Owl",
    cleanliness: "Neat",
    studyHabits: "Quiet Study",
    cgpa: 9.5,
    hometown: "Chandigarh",
    matchScore: 85,
    avatar: "KS",
    avatarColor: "bg-violet-500",
    allocationStatus: "Allocated",
    matchStatus: "Matched",
  },
  {
    id: 6,
    name: "Ananya Joshi",
    regNo: "12314156",
    email: "ananya.joshi@lpu.in",
    program: "BCA",
    school: "School of Computer Applications",
    year: 2,
    gender: "Female",
    roomPreference: "Double",
    hostelBlock: "37",
    roomNo: null,
    interests: ["UI Design", "Reading", "Music"],
    sleepSchedule: "Early Bird",
    cleanliness: "Very Neat",
    studyHabits: "Solo Study",
    cgpa: 8.1,
    hometown: "Pune",
    matchScore: 79,
    avatar: "AJ",
    avatarColor: "bg-rose-500",
    allocationStatus: "Pending",
    matchStatus: "Looking",
  },
  {
    id: 7,
    name: "Dev Malhotra",
    regNo: "12312677",
    email: "dev.malhotra@lpu.in",
    program: "B.Tech (EE)",
    school: "School of Electronics & Electrical Engineering",
    year: 3,
    gender: "Male",
    roomPreference: "Double",
    hostelBlock: "38",
    roomNo: null,
    interests: ["Basketball", "Robotics", "Anime"],
    sleepSchedule: "Night Owl",
    cleanliness: "Moderate",
    studyHabits: "Group Study",
    cgpa: 7.5,
    hometown: "Jaipur",
    matchScore: 72,
    avatar: "DM",
    avatarColor: "bg-cyan-500",
    allocationStatus: "Pending",
    matchStatus: "Looking",
  },
  {
    id: 8,
    name: "Ishita Gupta",
    regNo: "12311988",
    email: "ishita.gupta@lpu.in",
    program: "B.Tech (CSE-DS)",
    school: "School of Computer Science & Engineering",
    year: 4,
    gender: "Female",
    roomPreference: "Single",
    hostelBlock: "39",
    roomNo: "39-215",
    interests: ["Research", "Painting", "Hiking"],
    sleepSchedule: "Early Bird",
    cleanliness: "Very Neat",
    studyHabits: "Quiet Study",
    cgpa: 9.0,
    hometown: "Kolkata",
    matchScore: 83,
    avatar: "IG",
    avatarColor: "bg-teal-500",
    allocationStatus: "Allocated",
    matchStatus: "Matched",
  },
];

/** LPU Hostel blocks — Boys: even numbers, Girls: odd numbers */
export const hostelBlocks = [
  { block: "32", name: "Block 32 (Boys)", gender: "Male",   totalRooms: 120, occupied: 98 },
  { block: "34", name: "Block 34 (Boys)", gender: "Male",   totalRooms: 120, occupied: 105 },
  { block: "33", name: "Block 33 (Girls)", gender: "Female", totalRooms: 100, occupied: 87 },
  { block: "35", name: "Block 35 (Girls)", gender: "Female", totalRooms: 100, occupied: 91 },
];

/** Summary stats derived from mockStudents */
export const mockStats = {
  totalStudents: mockStudents.length,
  allocated: mockStudents.filter((s) => s.allocationStatus === "Allocated").length,
  pending:   mockStudents.filter((s) => s.allocationStatus === "Pending").length,
  matched:   mockStudents.filter((s) => s.matchStatus === "Matched").length,
  looking:   mockStudents.filter((s) => s.matchStatus === "Looking").length,
};
